language: python
email:
    recipients:
      - OMC-team@cern.ch
      - efol@cern.ch
    on_success: always
    on_failure: always
python:
 - "2.7"
script:
 - pytest tests/unit/
 - pytest -s tests/accuracy/
 - python tests/regression/test_cases.py
 - travis-sphinx build --source=doc/ --nowarn
after_success:
 - travis-sphinx deploy
git:
    depth: false
regression:
    ref_commit: ceb509ed43333876682becaafb46295e61fbbc2f
