language: python
email:
    recipients:
      - OMC-team@cern.ch
      - efol@cern.ch
    on_success: always
    on_failure: always
python:
 - "2.7"
script:
 - python tests/regression/test_cases.py
 - pytest tests/accuracy/
 - pytest tests/unit/
 - travis-sphinx build --source=doc/ --nowarn
after_success:
 - travis-sphinx deploy
git:
    depth: false
regression:
    ref_commit: 342a75e4ba1ee526b051ecc074dbccfbe3575f13
